AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  ExpressApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/app.lambdaHandler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Environment:
        Variables:
          PORT: "6500"
          MONGO_URI: !Sub "{{resolve:secretsmanager:lenslyst/prod/secrets:SecretString:MONGO_URI}}"
          JWT_SECRET: !Sub "{{resolve:secretsmanager:lenslyst/prod/secrets:SecretString:JWT_SECRET}}"
          AWS_BUCKET_NAME: "micbucket123"
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://www.buknr.com,http://localhost:3000'"
        AllowCredentials: true

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  ExpressApiFunction:
    Description: "Express API Lambda Function ARN"
    Value: !GetAtt ExpressApi.Arn
