GET http://localhost:6500/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpwWkNJNklqWTNPRFV6TjJNNU5Ea3lNRFEzWXpJeFptSXpNVEpoTnlJc0luSnZiR1VpT2lKamNtVmhkRzl5SWl3aWFXRjBJam94TnpNNE5EYzNPRGt4TENKbGVIQWlPakUzTnpBd016VTBPVEY5LjZ2ZXFpR0xqVVFtdFlKY08wTmpxeHlGNVpjR3F3V3cySVdJNV9JQVBTTWciLCJpYXQiOjE3Mzg0Nzc4OTEsImV4cCI6MTczOTA4MjY5MX0.DsS8nSckqSUtBtcwrLsSz8P1c9yfURyUotv7Z443MfA